export const DATA_FETCHING_STARTED = 'DATA_FETCHING_STARTED';
export const DATA_FETCHING_SUCCESS = 'DATA_FETCHING_SUCCESS';
export const DATA_FETCHING_FAILED = 'DATA_FETCHING_FAILED';

// Cart
export const DELETE_ITEM = 'DELETE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';
export const ENCREASE_QTY = 'ENCREASE_QTY';
export const DECREASE_QTY = 'DECREASE_QTY';
export const TOTAL_PRICE = 'TOTAL_PRICE';
export const COUNTER = 'COUNTER';
